import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <main className='big-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>develeped by Allen</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pinter text-2xl'/></li>
              <li><a className='bg-cyan-500 px-4 py-2 text-white rounded-md ml-8'  href="#">Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>
    </>
  )
}
